# Generated by Django 4.1 on 2023-10-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_advisor_user_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usergroup',
            field=models.CharField(choices=[('Co', 'Consumer'), ('Ad', 'Advisor')], default='Co', max_length=56),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
