# Generated by Django 4.1 on 2023-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usergroup',
            field=models.CharField(choices=[('Consumer', 'Consumer'), ('Advisor', 'Advisor')], default='Consumer', max_length=56),
        ),
    ]
