# Generated by Django 4.1 on 2023-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfundsapp', '0003_order_link_alter_order_buyer_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link',
            field=models.CharField(default='4061a199-b90f-4233-abb1-1b2dddf53925', max_length=100, unique=True),
        ),
    ]
